name: Azure Web App Container

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/setup-buildx-action@v1
      
      - name: AZ CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Log in to ACR
        run: |
          az acr login -n ahugheswebappcontainerdev
      
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            "SUBSCRIPTION_ID=${{ secrets.AZURE_SUB_ID}}"
          push: true
          tags: ahugheswebappcontainerdev.azurecr.io/ahugheswebappcontainer/helloworld:${{ github.sha }}
          file: ./Dockerfile
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: AZ CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ahugheswebappcontainer'
        slot-name: 'staging'
        images: ahugheswebappcontainerdev.azurecr.io/ahugheswebappcontainer/helloworld:${{ github.sha }}
        
  release:
    runs-on: ubuntu-latest
    needs: deploy
    environment: production
    
    steps:
    - name: AZ CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUB_ID }}
    - name: Swap Staging Slot to Production
      run: |
          az webapp deployment slot swap --slot 'staging' --name ahugheswebappcontainer --resource-group ahughes-webappcontainer-wus3-rg
